---
title: "Test"
date: 2019-02-11
---

title: Introduction to my new first website!
author: 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Find some interesting information about informatics and telecomunications. 
  Everything you are looking for is in this awesome website.

# social links
twitter_username: @twitter
github_username:  @albertpb98

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
